import * as React from "react";

const LoadingIcon = ({ className = "w-8 h-8", ...props }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="#E90D1AFF"
    viewBox="0 0 24 24"
    className={className}
    {...props}
  >
    <circle cx="4" cy="12" r="0">
      <animate
        fill="freeze"
        attributeName="r"
        begin="0;spinner_z0Or.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_OLMs.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_UHR2.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
      ></animate>
      <animate
        id="spinner_lo66"
        fill="freeze"
        attributeName="r"
        begin="spinner_Aguh.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
      ></animate>
      <animate
        id="spinner_z0Or"
        fill="freeze"
        attributeName="cx"
        begin="spinner_lo66.end"
        dur="0.001s"
        values="20;4"
      ></animate>
    </circle>
    <circle cx="4" cy="12" r="3">
      <animate
        fill="freeze"
        attributeName="cx"
        begin="0;spinner_z0Or.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_OLMs.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
      ></animate>
      <animate
        id="spinner_JsnR"
        fill="freeze"
        attributeName="r"
        begin="spinner_UHR2.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
      ></animate>
      <animate
        id="spinner_Aguh"
        fill="freeze"
        attributeName="cx"
        begin="spinner_JsnR.end"
        dur="0.001s"
        values="20;4"
      ></animate>
      <animate
        fill="freeze"
        attributeName="r"
        begin="spinner_Aguh.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
      ></animate>
    </circle>
    <circle cx="12" cy="12" r="3">
      <animate
        fill="freeze"
        attributeName="cx"
        begin="0;spinner_z0Or.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
      ></animate>
      <animate
        id="spinner_hSjk"
        fill="freeze"
        attributeName="r"
        begin="spinner_OLMs.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
      ></animate>
      <animate
        id="spinner_UHR2"
        fill="freeze"
        attributeName="cx"
        begin="spinner_hSjk.end"
        dur="0.001s"
        values="20;4"
      ></animate>
      <animate
        fill="freeze"
        attributeName="r"
        begin="spinner_UHR2.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_Aguh.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
      ></animate>
    </circle>
    <circle cx="20" cy="12" r="3">
      <animate
        id="spinner_4v5M"
        fill="freeze"
        attributeName="r"
        begin="0;spinner_z0Or.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="3;0"
      ></animate>
      <animate
        id="spinner_OLMs"
        fill="freeze"
        attributeName="cx"
        begin="spinner_4v5M.end"
        dur="0.001s"
        values="20;4"
      ></animate>
      <animate
        fill="freeze"
        attributeName="r"
        begin="spinner_OLMs.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="0;3"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_UHR2.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="4;12"
      ></animate>
      <animate
        fill="freeze"
        attributeName="cx"
        begin="spinner_Aguh.end"
        calcMode="spline"
        dur="0.5s"
        keySplines=".36,.6,.31,1"
        values="12;20"
      ></animate>
    </circle>
  </svg>
);

export default LoadingIcon;
